name: Super-Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false # Set to true to scan the whole repo, false to only scan changed files
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          
          # Optional: Turn off linters you don't need to speed up the run
          VALIDATE_JSCPD: false 
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_TYPESCRIPT_ES: true
